# -*- coding: utf-8 -*-
"""Builds final Tuore recipe objects from the selected, cleanly-mapped K-Ruoka
recipes. Names are our own hand-translations (name_en.py) of K-Ruoka's dish
titles (facts, not protected expression); steps are freshly generated by the
existing archetype-based template engine (shared with the Food.com pipeline)
from the ingredient composition -- never copied/paraphrased from K-Ruoka's
own written instructions. Macros (protein/carbs/fat/kcal) and serving counts
are K-Ruoka's real per-serving nutrition data, which is strictly more
accurate than the heuristic PROTEIN_G/CARB_G/FAT_G tables used elsewhere."""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent / "data"))

from recipe_lib import P, FRAC, is_vegan, is_veg, price_per_serving, make_id
from generate_from_foodcom import classify, gen_steps, icon_for, ARCHETYPE_TYPE
from map_ingredients import classify as classify_ingredient
from name_en import NAME_EN

DEFAULT_FRAC = {'berries': 0.25, 'oatcream': 0.2, 'flour': 0.2, 'darkchocolate': 0.15}


def frac_for(ref):
    return FRAC.get(ref, DEFAULT_FRAC.get(ref, 0.3))


def parse_time(prep_time_fi):
    if not prep_time_fi:
        return None
    s = prep_time_fi.lower()
    nums = [int(n) for n in re.findall(r'\d+', s)]
    if 'alle' in s and nums:
        return max(10, nums[0] - 5)
    if 'yli' in s and nums:
        return nums[0] + 15
    if len(nums) >= 2:
        return round((nums[0] + nums[1]) / 2)
    if nums:
        return nums[0]
    return None


def main():
    selected = json.load(open(Path(__file__).parent / "selected_recipes.json", encoding="utf-8"))
    html = open(r"C:\Users\swath\tuore-app\index.html", encoding="utf-8").read()
    existing_ids = set(re.findall(r"\{id:'(\w+)'", html))
    used_ids = set(existing_ids)

    out = []
    skipped_servings = 0
    for r in selected:
        smin = r.get('servingCountMin')
        if not smin or smin < 1 or smin > 8:
            skipped_servings += 1
            continue

        mapped_refs = []
        for ing in r.get('ingredients') or []:
            sp = (ing.get('productSpelling') or {}).get('fi')
            if not sp:
                continue
            kind, val = classify_ingredient(sp)
            if kind == 'mapped' and val not in mapped_refs:
                mapped_refs.append(val)
        refs = sorted(set(mapped_refs))

        archetype = classify(refs)
        steps, equip = gen_steps(archetype, refs, None)
        icon = icon_for(refs, archetype)
        mtype = ARCHETYPE_TYPE[archetype]

        kcal = r.get('energyKcalPerServing')
        protein = r.get('proteinPerServing')
        carbs = r.get('carbohydratePerServing')
        fat = r.get('fatPerServing')
        if kcal is None or protein is None or carbs is None or fat is None:
            continue

        servings = smin
        time = parse_time((r.get('prepTime') or {}).get('fi')) or 25
        time = max(5, min(90, round(time / 5) * 5))

        ing = [{'ref': ref, 'frac': frac_for(ref)} for ref in refs]
        pps = price_per_serving([(i['ref'], i['frac']) for i in ing], servings)

        filters = []
        tags = []
        if is_vegan(refs):
            filters.append('vegan'); tags.append('Vegan')
        elif is_veg(refs):
            filters.append('veg'); tags.append('Vegetarian')
        if protein >= 18:
            filters.append('protein'); tags.append('Protein')
        if carbs <= 15:
            filters.append('lowcarb'); tags.append('Low-carb')
        if time <= 15:
            filters.append('quick'); tags.append('Quick')
        if pps < 2.5:
            filters.append('budget')
        if not tags:
            tags = ['Hearty']
        tags = tags[:2]

        name = NAME_EN.get(r['recipeId'])
        if not name:
            continue

        pictures = r.get('pictures') or []
        photo_id = pictures[0]['id'] if pictures else None

        cid = make_id(['kr', archetype] + refs, used_ids)
        out.append({
            'id': cid, 'name': name, 'icon': icon, 'type': mtype,
            'filters': filters, 'tags': tags, 'time': int(time),
            'protein': round(protein), 'carbs': round(carbs), 'fat': round(fat),
            'kcal': round(kcal), 'servings': servings, 'equip': equip,
            'steps': steps, 'ing': ing,
            'photo': photo_id,
        })

    print(f"Built {len(out)} recipes (skipped {skipped_servings} for serving-count outliers)")
    from collections import Counter
    type_count = Counter()
    for r in out:
        for t in r['type']:
            type_count[t] += 1
    print('by type:', dict(type_count))
    has_photo = sum(1 for r in out if r['photo'])
    print(f'with photo: {has_photo}/{len(out)}')

    json.dump(out, open(Path(__file__).parent / "kruoka_recipes.json", "w", encoding="utf-8"), ensure_ascii=False)
    print("Saved kruoka_recipes.json")


if __name__ == "__main__":
    main()
